name: Publish latest build

on:
  push:
    branches: [master]

jobs:
  deploy:
    if: ${{ github.repository == 'SpoonLabs/gumtree-spoon-ast-diff' }}
    name: 'Publish package'
    runs-on: ubuntu-latest

    steps:
    - name: Wait for tests to pass
      uses: lewagon/wait-on-check-action@v1.1.1
      with:
        ref: ${{ github.ref }}
        running-workflow-name: 'Publish package'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Start deployment
      run: .buildscript/deploy_to_maven.sh
